---
- name: Backup Device configuration
  hosts: switches
  gather_facts: no
  vars:
    ansible_become: yes # Required for privilege escalation
    ansible_become_method: enable
    ansible_become_pass: "admin-123"
  tasks:
    - name: Backup configuration
      cisco.ios.ios_config:
        backup: yes
      register: backup_result

    - name: Display backup result
      debug:
        var: backup_result
