- name: Test connectivity to Cisco switch
  hosts: switches
  gather_facts: no
  tasks:
    - name: Test if the switch is reachable
      ansible.builtin.ping:

    - name: Run 'show version' command on the switch
      cisco.ios.ios_command:
        commands:
          - show version
      register: result

    - name: Display the result
      debug:
        var: result
