---
- name: Test connectivity to Cisco switch
  hosts: switches
  gather_facts: no
  collections:
    - cisco.ios
  tasks:
    - name: Run 'show version' command on the switch
      ios_command:
        commands:
          - show version
