---
- name: Test Cisco IOS Facts
  hosts: switches
  gather_facts: no
  vars: # for execution environment

    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.ios.ios
    ansible_become: yes
    ansible_become_method: enable
    ansible_become_pass: "admin-123"
    ansible_command_timeout: 60
  tasks:
    - name: Gather facts from Cisco switch
      cisco.ios.ios_facts:
      register: switch_facts

    - name: Display gathered facts
      debug:
        var: switch_facts
#      vars:

    - name: Run 'show vlan brief' command
      cisco.ios.ios_command:
        commands:
          - show vlan brief
      register: vlan_output

    - name: Parse VLAN output and display VLAN count and descriptions
      debug:
        msg: >
          VLAN Count: {{ vlan_output.stdout[0].splitlines()[2:] | length }}
          VLANs:
          {{ vlan_output.stdout[0].splitlines()[2:] | map('split') | map('join', ': ') | join('\n') }}

